//
//  TTTViewController.m
//  Pshare
//
//  Created by Tiago Magalhães on 29/05/16.
//  Copyright © 2016 Tiago Magalhães. All rights reserved.
//

#import "TTTViewController.h"

@interface TTTViewController ()
@end

@implementation TTTViewController

// @synthesize means "create getter and setter" methods.
@synthesize s1,s2,s3,s4,s5,s6,s7,s8,s9;
@synthesize oImg, xImg, theImg, whoseTurn, board;
@synthesize resetBtn, myAlertView;


- (void)viewDidLoad {
    oImg = [UIImage imageNamed:@"circle.png"];
    xImg = [UIImage imageNamed:@"cross.png"];
    
    playerToken=1;
    
    WhoseTurn.text = @"X can go";
    
    numberOfPlays=0;
    
    
    [super viewDidLoad]; // Autogenerated.
}


- (void)touchesBegan:(NSSet *)touches withEvent:(UIEvent *)event{
    if (playerToken == 1) {
        theImg = xImg;
    } else if (playerToken == 2) {
        theImg = oImg;
    }
    
    UITouch *touch = [[event allTouches] anyObject];
    cellWasUsed = NO;
    
    if (CGRectContainsPoint([s1 frame], [touch locationInView:self.view])&(s1.image == NULL)){
        cellWasUsed=YES;
        s1.image=theImg;
    }
    
    
    if (CGRectContainsPoint([s2 frame], [touch locationInView:self.view])&(s2.image == NULL)){
        cellWasUsed=YES;
        s2.image=theImg;
    }
    
    if (CGRectContainsPoint([s3 frame], [touch locationInView:self.view])&(s3.image == NULL)){
        cellWasUsed=YES;
        s3.image=theImg;
    }
    
    if (CGRectContainsPoint([s4 frame], [touch locationInView:self.view])&(s4.image == NULL)){
        cellWasUsed=YES;
        s4.image=theImg;
    }
    
    if (CGRectContainsPoint([s5 frame], [touch locationInView:self.view])&(s5.image == NULL)){
        cellWasUsed=YES;
        s5.image=theImg;
    }
    
    if (CGRectContainsPoint([s6 frame], [touch locationInView:self.view])&(s6.image == NULL)){
        cellWasUsed=YES;
        s6.image=theImg;
    }
    
    if (CGRectContainsPoint([s7 frame], [touch locationInView:self.view])&(s7.image == NULL)){
        cellWasUsed=YES;
        s7.image=theImg;
    }
    
    if (CGRectContainsPoint([s8 frame], [touch locationInView:self.view])&(s8.image == NULL)){
        cellWasUsed=YES;
        s8.image=theImg;
    }
    
    if (CGRectContainsPoint([s9 frame], [touch locationInView:self.view])&(s9.image == NULL)){
        cellWasUsed=YES;
        s9.image=theImg;
    }
    
    [self processingLogic];
    
    if (cellWasUsed)
    {
        [self updatePlayerInfo];
    }
    
}


-(void) processingLogic{
    if ([self checkForWin])
    {
        if (playerToken==1)
        {
        myAlertView = [[UIAlertView alloc] initWithTitle:@"Winner!" message:@ "X won!" delegate:self cancelButtonTitle:@"OK" otherButtonTitles:nil, nil];
            [myAlertView show];
            [self ResetBoard];
        }
        else if (playerToken==1)
        {
            myAlertView = [[UIAlertView alloc] initWithTitle:@"Winner!" message:@ "O won!" delegate:self cancelButtonTitle:@"OK" otherButtonTitles:nil, nil];
            [myAlertView show];
            [self ResetBoard];
        }
        if (numberOfPlays==9)
        {
            myAlertView = [[UIAlertView alloc] initWithTitle:@"No Winner!" message:@ "Draw!" delegate:self cancelButtonTitle:@"OK" otherButtonTitles:nil, nil];
            [myAlertView show];
            [self ResetBoard];
        }
    }
}

-(BOOL) checkForWin{
    
    
    if(s1.image != NULL) {
        if (((s1.image == s2.image) && (s1.image == s3.image)) ||
            ((s1.image == s4.image) && (s1.image == s7.image))) {
            return YES;
        }
    }
    
    
    //Check for wins that goe through the middle of the board.
    
    if(s5.image != NULL) {
        if (((s5.image == s4.image) && (s5.image == s6.image)) ||
            ((s5.image == s2.image) && (s5.image == s8.image)) ||
            ((s5.image == s1.image) && (s5.image == s9.image)) ||
            ((s5.image == s3.image) && (s5.image == s7.image))) {
            return YES;
        }
    }
    
    
    // Check for win in the rightmost column and in the lowest row.
    
    if(s9.image != NULL) {
        if (((s9.image == s6.image) && (s9.image == s3.image)) ||
            ((s9.image == s8.image) && (s9.image == s7.image))) {
            return YES;
        }
    }
    
    return NO;

    
}

-(void) displayWinner{
 if ([self checkForWin]==YES)
     if (playerToken ==1){
         whoseTurn.text = @"X is the Winner!";
     }
     else{
         whoseTurn.text = @"O is the Winner!";
    }
    
}

-(IBAction)buttonReset{
    [self ResetBoard];
}

-(void) ResetBoard
{
    s1.image=NULL;
    s2.image=NULL;
    s3.image=NULL;
    s4.image=NULL;
    s5.image=NULL;
    s6.image=NULL;
    s7.image=NULL;
    s8.image=NULL;
    s9.image=NULL;
    
    playerToken=1;
    whoseTurn.text =@"X can go";
    numberOfPlays=0;
    
    
}

-(void) updatePlayerInfo{
    numberOfPlays++;
    if (numberOfPlays==9)
    {
        [self ResetBoard];
        
    }
    
    if (playerToken==1)
    {
        playerToken=2;
        whoseTurn.text = @"O can go!";
    }else{
        playerToken=1;
        whoseTurn.text = @"X can go!";
    }
    
}


/*

-(void)slot:(UIImageView *)slot wasTouched:(UITouch *)touch {
    if ((slot.image == NULL) &&
        CGRectContainsPoint([slot frame], [touch locationInView:self.view])) {
        slot.image = imageToPlace;
        round++;
        [self gameStatus];
    }
}

-(void)gameStatus{
    BOOL win = [self somebodyWon];
    if (round == 9 || win) {
        myAlertView = nil;
        NSString *result = nil;
        if (round == 9 && !win) {
            result = @"Draw!";
        }
        else if (round <= 9 && win){
            if(player == 1){
                result = @"Player 1 won!";
            }
            else if(player == 2){
                result = @"Player 2 won!";
            }
        }
        else {
            result = @"Sorry! Something went wrong when determining win/draw situation.";
        }
        myAlertView = [[UIAlertView alloc] initWithTitle:@"Result:" message:result delegate:self cancelButtonTitle:@"Ok!" otherButtonTitles:nil, nil];
        [myAlertView show];
        [self resetBoard];
    } else {
        [self switchPlayers];
    }
}
 
 */

/*
-(BOOL)somebodyWon{
 
     //Check for win in the leftmost column and in the topmost row.
 
    if(s1.image != NULL) {
        if (((s1.image == s2.image) && (s1.image == s3.image)) ||
            ((s1.image == s4.image) && (s1.image == s7.image))) {
            return YES;
        }
    }
    
 
     //Check for wins that goe through the middle of the board.
 
    if(s5.image != NULL) {
        if (((s5.image == s4.image) && (s5.image == s6.image)) ||
            ((s5.image == s2.image) && (s5.image == s8.image)) ||
            ((s5.image == s1.image) && (s5.image == s9.image)) ||
            ((s5.image == s3.image) && (s5.image == s7.image))) {
            return YES;
        }
    }
    
 
     // Check for win in the rightmost column and in the lowest row.
 
    if(s9.image != NULL) {
        if (((s9.image == s6.image) && (s9.image == s3.image)) ||
            ((s9.image == s8.image) && (s9.image == s7.image))) {
            return YES;
        }
    }
    
    return NO;
}

- (IBAction)resetButton:(id)sender {
    [self resetBoard];
}

//-(IBAction)buttonReset{
//    [self resetBoard];
//}

-(void)resetBoard{
    s1.image = NULL;
    s2.image = NULL;
    s3.image = NULL;
    s4.image = NULL;
    s5.image = NULL;
    s6.image = NULL;
    s7.image = NULL;
    s8.image = NULL;
    s9.image = NULL;
    
    player = 1;
    msg.text = @"Player 1: Put a \"Cross\" on the field";
    round = 0;
}

-(void)switchPlayers{
    if (player == 1){
        player = 2;
        msg.text = @"Player 2: Put a \"Circle\" on the field";
    } else {
        player = 1;
        msg.text = @"Player 1: Put a \"Cross\" on the field";
    }
}

- (void)viewDidUnload
{
    [super viewDidUnload];
    // Release any retained subviews of the main view.
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation
{
    return (interfaceOrientation != UIInterfaceOrientationPortraitUpsideDown);
}
 
 */

@end